<?php
$title = 'My Actors';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('actors', ['action' => 'add']) ?>">Add new Actor</a>
</p>

<table class="table">
    <tr>
        <th>Last Name</th>
        <th>First Name</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->actors as $actor) : ?>
        <?php /** @var \Actor\Model\Actor $prod */ ?>
        <tr>
            <td><?= $this->escapeHtml($actor->getLastName()) ?></td>
            <td><?= $this->escapeHtml($actor->getFirstName()) ?></td>
            <td>
                <a href="<?= $this->url('actors', ['action' => 'edit', 'id' => $actor->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('actors', ['action' => 'delete', 'id' => $actor->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
