<?php

$title = 'Edit Tag';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
/** @var \Zend\Form\Form $tag */
$tag = $this->form->get('label');
$tag->setAttribute('class', 'form-control');
$tag->setAttribute('placeholder', 'Album title');

/** @var \Zend\Form\Form $submit */
$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute(
    'action', $this->url(
    'tags', [
        'action' => 'edit',
        'id'     => $this->id,
    ]
)
);
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
    <div class="form-group">
        <?= $this->formLabel($tag) ?>
        <?= $this->formElement($tag) ?>
        <?= $this->formElementErrors()->render($tag, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
